name: Test & Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt install clang cmake

      - name: Run opt test script
        run: |
          cd SysYF_Pass_Student/test/student && sh eval.sh

  wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install clang cmake

      - name: Pull image
        run: |
          docker pull emscripten/emsdk

      - name: build wasm
        run: |
          cd SysYF_Pass_Student && docker run \
            --rm \
            -v $(pwd):/src \
            -u $(id -u):$(id -g) \
            emscripten/emsdk \
            sh build_wasm.sh

      - name: collect dists
        run: |
          cp SysYF_Pass_Student/build/compiler.js dists/ && \
          cp SysYF_Pass_Student/build/compiler.wasm dists/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: static
          FOLDER: dists
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
